### ISSUE TITLE
One image has OLED and no WAN, other image has WAN and no OLED

### ISSUE THREAD

**Issue by hagensieker** [geeekpi/cm4routerboard#5]
openwrt-bcm27xx-bcm2711-rpi-4-ext4-with_oled096_factory.img allows OLED to work but no eth1 WAN

openwrt-bcm2711-rpi-4-ext4-rtl8168-factory.img has operational WAN port but OLED won't work.

Is there an image that has working OLED and eth1 Wan port?

**Comment by hagensieker** [comment]
Never mind.  I saw this reply in another issue. 

`Default image has /dev/i2c-1 but /usr/bin/oled is compiled with /dev/i2c-0. Adding a symbolic link works. To make it persistent, easiest is to add to the start() function in /etc/init.d/oled:
ln -s /dev/i2c-1 /dev/i2c-0`

Everything is working now.

**Comment by Grimmy347** [comment]
> Never mind. I saw this reply in another issue.
> 
> `Default image has /dev/i2c-1 but /usr/bin/oled is compiled with /dev/i2c-0. Adding a symbolic link works. To make it persistent, easiest is to add to the start() function in /etc/init.d/oled: ln -s /dev/i2c-1 /dev/i2c-0`
> 
> Everything is working now.

Can you be more specific on how to make this change? Thank you!

**Comment by hagensieker** [comment]
I put the directions on my blog page:

https://www.hagensieker.com/wordpress/2022/02/22/geekpi-cm4-router-board-challenges/

**Comment by Grimmy347** [comment]
@hagensieker I tried what you had on your page but I still could not get the OLED to light up. I tried to do the chmod 755 /etc/init.d/oled and then /etc/init.d/oled restart but that gave me the error "uci: Entry into found" twice. I am not sure what that means or why it would say that. Any ideas about what I am missing? Thank you!

**Comment by Grimmy347** [comment]
I reflashed the board and I have stopped getting any errors but after taking all of the steps to enable the oled: /boot/config setting, the directions on hagensieker's page, the chmod 755 /etc/init.d./oled, restart and reboot, enabling in openwrt and so far nothing. I think the oled might be dead.

**Comment by hagensieker** [comment]
Go to your OLED page and make sure the "Enable" box is checked.

**Comment by Grimmy347** [comment]
Yeah, that was one of the first things I verified once I got that page to show up. I appreciate your help. Yesterday I decided to see if there was an issue with the OLED itself and so I checked the voltages going to it and it is receiving a signal so the issue is a dead OLED. I have a new one coming from Amazon tomorrow so we will see if my troubleshooting was correct.

**Comment by Grimmy347** [comment]
Received the replacement OLED today and it worked immediately. Thanks for the help and the link to your blog @hagensieker
