### ISSUE TITLE
Wireguard VPIN

### ISSUE THREAD

**Issue by David-McGuire** [geeekpi/cm4routerboard#7]
IM trying to install Wireguard on this and i am getting the following error
"kernel is not compatible, require 5.15.50-1-9ce438a9… while 5.10.90-1-96d73a40… is installed." 

I have tried to upgrade the Kerner via the "Software" option and I get errors on this as well.

will 5.18.9 be an upgradable version anytime soon?

**Comment by yoyojacky** [comment]
This problem is a system problem. You can try updating to the latest official Raspberry Pi system and try again. What does it have to do with the hardware? This is just an ioboard
