### ISSUE TITLE
Do any of the 64bit Pi OS Bookworm (Debian 12) binaries boot?

### ISSUE THREAD

**Issue by bigpcjunky** [geeekpi/cm4routerboard#9]
I know this is basically a dead product, but I wanted to see if any of the new bookworm builds of 64 bit Pi OS would boot.  No luck when getting the binaries through the Raspberry Pi Imager.  However, the Ubuntu 23.10 server for Pi version boots.  I wonder if something in the config.txt changed causing the CM4 board not to boot.  I know the Bullseye binary used to boot w/o problems.

**Comment by yoyojacky** [comment]
As long as the system supports CM4, it can start normally. The design of this baseboard is based on the official Raspberry Pi IOboard. What can't be started? Have you tried it? Why do you say it is a dead product?

**Comment by bigpcjunky** [comment]
Of course, it works on a real CM4 carrier board just like poe hat boards worked on the real CM4.  Did you forget the poe hat didn't work on your geeekpi/cm4 routerboard unless you cut some lines?
The question is did you try booting Pi OS 64 bit Bookworm on your routerboard?  Or was it like when you didn't test the pi poe hats on your board until many users complained?
I wrote Pi OS 64 bit Bookworm to emmc on the cm4 on your router board using the Raspberry Pi Imager.  I tried both desktop and Lite versions.  I'm connecting as terminal via ssh.  I got 'Connection failed.  FlowSocketConnector: Failed to connect to target address.  Windows error 10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'  I tried to connect many times.

I then swapped the same cm4 board into a real Pi CM4 io/carrier board and it boots fine.  Ubuntu 23.10 downloaded with the Pi Imager does work with your carrier board and Debian 11/Bullseye also worked on your board, so I assume maybe something in the config.txt file changed or Raspberry Pi org removed code that was in Bullseye that worked on 3rd party hardware from the Bookworm release.  Since Ubuntu 23.10 (Debian 12) works I assume the code is still there.
I should have asked for a refund for your crap product and support.  It's not my job to find bugs in your products.


    On Monday, April 8, 2024 at 10:12:57 PM PDT, yoyojacky ***@***.***> wrote:  
 
 


Closed #9 as completed.

**Comment by yoyojacky** [comment]
> Of course, it works on a real CM4 carrier board just like poe hat boards worked on the real CM4.  Did you forget the poe hat didn't work on your geeekpi/cm4 routerboard unless you cut some lines? The question is did you try booting Pi OS 64 bit Bookworm on your routerboard?  Or was it like when you didn't test the pi poe hats on your board until many users complained? I wrote Pi OS 64 bit Bookworm to emmc on the cm4 on your router board using the Raspberry Pi Imager.  I tried both desktop and Lite versions.  I'm connecting as terminal via ssh.  I got 'Connection failed.  FlowSocketConnector: Failed to connect to target address.  Windows error 10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'  I tried to connect many times. I then swapped the same cm4 board into a real Pi CM4 io/carrier board and it boots fine.  Ubuntu 23.10 downloaded with the Pi Imager does work with your carrier board and Debian 11/Bullseye also worked on your board, so I assume maybe something in the config.txt file changed or Raspberry Pi org removed code that was in Bullseye that worked on 3rd party hardware from the Bookworm release.  Since Ubuntu 23.10 (Debian 12) works I assume the code is still there. I should have asked for a refund for your crap product and support.  It's not my job to find bugs in your products. On Monday, April 8, 2024 at 10:12:57 PM PDT, yoyojacky ***@***.***> wrote: Closed #9 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Sorry for giving you a bad experience. In fact, if you cannot connect through SSH, I don’t know if you have enabled the ssh service. I am not sure what you have done, such as detailed steps? If you use bullseye, you may need to recompile the kernel, because the official system of Raspberry Pi does not configure the driver corresponding to the network card and the driver corresponding to OLED. If you need it to run on bookworm, I can give you a pre-installed one. Mirror, install the driver, and help you light up the OLED screen. If you really cannot use the device, please contact our sales. We are willing to handle the return and refund process for you. Thank you for your reply.

**Comment by bigpcjunky** [comment]
I'm not an idiot.  I probably have many more years of experience than you.  I told you Ubuntu 23.10 works on your board and I also swapped the same CM4 board with Bookworm installed into a real PI CM4 io board and it boots fine.  So SSH is enabled and working fine.  I access everything by SSH so I have no use for the OLED display.  I expect that the eth0 port should work w/o custom drivers and kernel builds if your router board is truly compatible with the Pi CM4 io board.
I'm already happy using the real CM4 io board and a Pi 4.  I bought your Router board because I thought it might be a faster/better solution than the Pi CM4 io board, but it wasn't worth the time and trouble when poe didn't work.  I usually keep it in the box and never use it.  I only took it out to test when Raspberry Pi released Debian 12/Bookworm because it is supposed to be faster than Debian 11/Bullseye for networking.  I wasted so much time trying to get it to work on your board.  That's why I left a message so many months ago asking if anyone was able to boot Pi Bookworm.  Do I contact sales @ Seeed Studio?
Thanks
    On Tuesday, April 9, 2024 at 10:40:20 PM PDT, yoyojacky ***@***.***> wrote:  
 
 



Of course, it works on a real CM4 carrier board just like poe hat boards worked on the real CM4.  Did you forget the poe hat didn't work on your geeekpi/cm4 routerboard unless you cut some lines? The question is did you try booting Pi OS 64 bit Bookworm on your routerboard?  Or was it like when you didn't test the pi poe hats on your board until many users complained? I wrote Pi OS 64 bit Bookworm to emmc on the cm4 on your router board using the Raspberry Pi Imager.  I tried both desktop and Lite versions.  I'm connecting as terminal via ssh.  I got 'Connection failed.  FlowSocketConnector: Failed to connect to target address.  Windows error 10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'  I tried to connect many times. I then swapped the same cm4 board into a real Pi CM4 io/carrier board and it boots fine.  Ubuntu 23.10 downloaded with the Pi Imager does work with your carrier board and Debian 11/Bullseye also worked on your board, so I assume maybe something in the config.txt file changed or Raspberry Pi org removed code that was in Bullseye that worked on 3rd party hardware from the Bookworm release.  Since Ubuntu 23.10 (Debian 12) works I assume the code is still there. I should have asked for a refund for your crap product and support.  It's not my job to find bugs in your products. On Monday, April 8, 2024 at 10:12:57 PM PDT, yoyojacky @.> wrote: Closed #9 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>


Sorry for giving you a bad experience. In fact, if you cannot connect through SSH, I don’t know if you have enabled the ssh service. I am not sure what you have done, such as detailed steps? If you use bullseye, you may need to recompile the kernel, because the official system of Raspberry Pi does not configure the driver corresponding to the network card and the driver corresponding to OLED. If you need it to run on bookworm, I can give you a pre-installed one. Mirror, install the driver, and help you light up the OLED screen. If you really cannot use the device, please contact our sales. We are willing to handle the return and refund process for you. Thank you for your reply.
